services:
  db:
    image: postgres:15
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # DATABASE PERSISTS HERE

  backend:
    build: ./backend
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/mydb
      TZ: Asia/Kolkata
    ports:
      - "3000:8000"
      - "5678:5678"  # For debugging
    volumes:
      - ./backend/src:/app  # CODE HOT RELOAD
      - alembic_versions:/app/alembic/versions  # MIGRATIONS PERSIST
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/usr/share/nginx/html  # FRONTEND HOT RELOAD

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_app
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:              # DATABASE DATA PERSISTS
  alembic_versions:    # MIGRATION FILES PERSIST  
  pgadmin_data:        # PGADMIN SETTINGS PERSIST
